package rules
import com.mastercard.filewatcherservice.model.TableNameCheckResult;

rule "Get table name GCMS_TRANSACTION_DETAIL"
	when
		tableCheckObject: TableNameCheckResult(type=="GCMSBA")
	then
		tableCheckObject.setTargetTableName("GCMS_TRANSACTION_DETAIL");
	end

rule "Get table name GCMS_BILLING_EVENT_DETAIL"
	when
		tableCheckObject: TableNameCheckResult(type=="GCMSBE")
	then
		tableCheckObject.setTargetTableName("GCMS_BILLING_EVENT_DETAIL");
	end